language: node_js
node_js:
  - "16"

cache:
  directories:
    - node_modules

stages:
  - install_dependencies
  - run_unit_tests
  - run_integration_tests

install_dependencies:
  stage: install_dependencies
  script:
    - npm install

run_unit_tests:
  stage: run_unit_tests
  script:
    - npm test -- --coverage --testPathPattern=src/__tests__/unit

run_integration_tests:
  stage: run_integration_tests
  script:
    - npm test -- --coverage --testPathPattern=src/__tests__/integration

notifications:
  email:
    recipients:
      - cquilaguy@unal.edu.co
    on_success: never
    on_failure: always

branches:
  only:
    - main
