apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  labels:
    app: reactapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: 982081055667.dkr.ecr.us-east-2.amazonaws.com/reactapp:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
  labels:
    app: reactapp
spec:
  type: LoadBalancer
  selector:
    app: reactapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
